### PR TITLE
Added the 24Hr Format

### PR DESCRIPTION
**Pull request by TheGlorySaint**
Added the 24Hr Format
Adjusted Version to 2.1.3

### CODE REVIEW

**Comment by GaspardMerten** [comment]
Hello @TheGlorySaint,

Thanks for the PR!

Could you please add the changes you made to the change log file ?

**Comment by TheGlorySaint** [comment]
for Sure

**Comment by TheGlorySaint** [comment]
Done

**Comment by GaspardMerten** [comment]
Thanks, merging now

**Pull request merged**
