### PR TITLE
[5.0.0] removed deprecated parameters

### PR DESCRIPTION
**Pull request by torbenkeller**
This removes the deprecated parameters from verison `4.0.0`.  We should give people time to migrate first and merge this in a month or so.

### CODE REVIEW

**Comment by GaspardMerten** [comment]
Yep! Thanks again.

**Comment by torbenkeller** [comment]
Closes #54

**Comment by GaspardMerten** [comment]
@torbenkeller, should we go through the removal of deprecated methods?

**Comment by torbenkeller** [comment]
@GaspardMerten Yes lets merge it

**Comment by GaspardMerten** [comment]
Done!

**Pull request merged**
